### ISSUE TITLE
Permission To Make An Unofficial Forge Version

### ISSUE THREAD

**Issue by Champe20** [HyperSoop/Simply-Optimized#13]
@HyperSoop May I use your Modpack's name and branding in an unofficial Forge version of your popular Fabric modpack Simply Optimized called Simply Optimized Reforged meant to be as close as possible using Forge versions or ports of all of its mods. Below is the logo I made for the project as a simple addition to Simply Optimized's logo:
![image](https://github.com/HyperSoop/Simply-Optimized/assets/117483128/6abb59e2-f85d-4806-80ab-d68d11737e40)

**Comment by HyperSoop** [comment]
considering the Forge mod loader would require an entirely different set of mods to replicate the optimizations from original SO, that'd be an entirely different modpack and logically should not use the same branding, especially if it's unaffiliated with the original. 

That is, you'd be better off making your modpack have unique branding and posing it not as a port of SO but rather as its own thing. If you plan on taking certain ideas or tweaks from SO where applicable, just leave a footnote in your modpack's description - and I don't see you reproducing SO on Forge well enough for it to qualify as a derivative rather than an unique work, so that's as far as you should probably go.

**Comment by Champe20** [comment]
I was able to use your the configs included with Simply Optimized and was able to use a Forge version or port of every mod included. If quality and similar is your concern please download my [modpack using this download link](https://cdn.modrinth.com/data/3iNoPG9J/versions/TYaLspN8/Simply%20Optimized%20Reforged-1.1.mrpack).

**Comment by HyperSoop** [comment]
even so, please do not use the same branding as mine. if you want to, you can credit me in the description for inspiration, but don't use the same branding.

**Comment by Champe20** [comment]
Thank you for your time.
