### ISSUE TITLE
New fabric api version crashes some mods on 1.21 and 1.21.1

### ISSUE THREAD

**Issue by girshcatt** [HyperSoop/Simply-Optimized#30]
Downgrade fabric api to 0.100.8+1.21, because new version crashing with some mods
[crash-2024-08-09_10.05.32-client.txt](https://github.com/user-attachments/files/16557375/crash-2024-08-09_10.05.32-client.txt)

**Comment by HyperSoop** [comment]
skill issue

**Comment by HyperSoop** [comment]
to elaborate, i don't want to account for what mods users might add locally in the way i maintain the base modpack, it'd be simply impossible to test every potential mod combination you could add to SO, hence you should be willing to work around issues caused by extra mods you've added to your instance in your instance
